CREATE TABLE `ARTICLE_REPLY` (
  `REPLY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(45) DEFAULT NULL,
  `REPLY_CONTENTS` varchar(1500) DEFAULT NULL,
  `REPLY_LIKES_COUNT` int(11) DEFAULT NULL,
  `REPLY_DISLIKES_COUNT` int(11) DEFAULT NULL,
  `ARTICLE_ID` int(11) DEFAULT NULL,
  `REPLY_WRITE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`REPLY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8;

select * from article;
select * from article_reply;

UPDATE ARTICLE_REPLY SET
		REPLY_LIKES_COUNT = REPLY_LIKES_COUNT + 1
		WHERE REPLY_ID = 36;