CREATE TABLE `ARTICLE` (
  `ARTICLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(45) DEFAULT NULL,
  `TITLE` varchar(45) DEFAULT NULL,
  `CONTENTS` varchar(45) DEFAULT NULL,
  `LIKES_COUNT` int(11) DEFAULT NULL,
  `READS_COUNT` int(11) DEFAULT NULL,
  `WRITE_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ARTICLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
